repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.3.12]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: ^tests/

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
    -   id: prettier
        types_or: [markdown, yaml, json, toml]
        args: [--prose-wrap=always, --print-width=88]

-   repo: local
    hooks:
    -   id: pytest
        name: run tests
        entry: pytest -v --cov=llm_list --cov-report=term-missing --cov-fail-under=80
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
