version: '3.8'

services:
  llm-list:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-list
    volumes:
      - ./data:/app/data  # Mount a volume for persistent data
    environment:
      - PYTHONUNBUFFERED=1
    # Uncomment and modify the command as needed
    # command: ["ollama", "--output-dir", "/app/data"]
    # For development with hot-reload:
    # command: ["uvicorn", "llm_list.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"  # Only needed if running a web server
    # Uncomment if you need to run as root (not recommended)
    # user: root
    restart: unless-stopped
    networks:
      - llm-net
    # Health check ensures the container is running properly
    healthcheck:
      test: ["CMD", "llm-list", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

# Uncomment and configure additional services as needed
#  redis:
#    image: redis:alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    networks:
#      - llm-net
#    restart: unless-stopped

networks:
  llm-net:
    driver: bridge

# Uncomment if using named volumes
#volumes:
#  redis_data:
